- hosts: raspberrypi
  become: true
  vars_files:
    - group_vars/all.yml
  roles:
    - role: python_venv
    - role: rpi_network
    - role: tor_ssh
    - role: hue_disco
    - role: web_interface
    - role: systemd_service
