---
- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart hue-bridge-direct-net
  ansible.builtin.systemd:
    name: hue-bridge-direct-net.service
    state: restarted
  when: rpi_network.enabled | default(false) | bool
  failed_when: false
