- name: Ensure base directory exists
  ansible.builtin.file:
    path: "{{ hue_disco_base_dir }}"
    state: directory
    mode: "0755"

- name: Install baseline packages
  ansible.builtin.package:
    name:
      - git
      - python3
    state: present
